const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const id=location.pathname.split("/").filter(Boolean).pop();let period=new URLSearchParams(location.search).get("period")||"24h";
const fmtTime=ts=>new Date(ts).toLocaleString("de-AT",period==="24h"?{hour:"2-digit",minute:"2-digit"}:{day:"2-digit",month:"2-digit",hour:"2-digit"});
function chartInner(block,d,ci){
 const datasets=[],bands=[];for(const it of block.items||[]){const pts=d.history[(it.source_index??0)+":"+it.key]||[],label=(it.label&&it.label.trim())?it.label.trim():it.key;if(!pts.length)continue;
  if(["binary","percent_binary"].includes(it.display)){bands.push({label,kind:"state",pts});continue}
  if(it.display==="mixer"){bands.push({label,kind:"mixer",pts});continue}
  const isPct=it.display==="percent"||String(it.key||"").includes("[%]");datasets.push({label,data:pts.map(p=>({x:Date.parse(p.time),y:p.value})),yAxisID:isPct?"yPct":"y",borderWidth:2,pointRadius:0,tension:.15,spanGaps:true});if(it.target_key){const tp=d.history[(it.target_source_index??it.source_index??0)+":"+it.target_key]||[];if(tp.length)datasets.push({label:label+" Soll",data:tp.map(p=>({x:Date.parse(p.time),y:p.value})),yAxisID:isPct?"yPct":"y",borderWidth:1.5,borderDash:[7,5],pointRadius:0,tension:.12,spanGaps:true})}
 }
 if(!datasets.length&&!bands.length)return'<div class="pv-empty">Keine Daten im gewählten Zeitraum.</div>';
 window.__chartConfigs=window.__chartConfigs||{};window.__chartConfigs[String(ci)]={datasets,bands};
 return'<div class="chartjs-wrap"><canvas id="chartjs'+ci+'"></canvas></div>'+(bands.length?'<div class="state-legend">'+(bands.some(b=>b.kind==="state")?'<span><i class="pump"></i>Pumpe EIN</span>':'')+(bands.some(b=>b.kind==="mixer")?'<span><i class="open"></i>Mischer AUF</span><span><i class="close"></i>Mischer ZU</span>':'')+'</div>':'')
}
function renderChartJs(ci){
 const cfg=window.__chartConfigs?.[String(ci)],canvas=document.getElementById("chartjs"+ci);if(!cfg||!canvas||!window.Chart)return;
 const hasPct=cfg.datasets.some(x=>x.yAxisID==="yPct");
 const bandPlugin={id:"insEiBands",beforeDatasetsDraw(chart){const {ctx,chartArea,scales}=chart,x=scales.x;if(!x||!cfg.bands.length)return;ctx.save();for(const b of cfg.bands){b.pts.forEach((p,i)=>{const v=Number(p.value);if((b.kind==="state"&&v<=0)||(b.kind==="mixer"&&v===0))return;const t=Date.parse(p.time),next=i+1<b.pts.length?Date.parse(b.pts[i+1].time):x.max,x1=Math.max(chartArea.left,x.getPixelForValue(t)),x2=Math.min(chartArea.right,x.getPixelForValue(next));if(x2<=x1)return;if(b.kind==="state"){ctx.fillStyle="rgba(67,211,140,0.055)";ctx.fillRect(x1,chartArea.top,x2-x1,chartArea.bottom-chartArea.top)}else{const mid=(chartArea.top+chartArea.bottom)/2;ctx.fillStyle=v>0?"rgba(233,120,85,0.20)":"rgba(59,142,219,0.20)";if(v>0)ctx.fillRect(x1,chartArea.top,x2-x1,mid-chartArea.top);else ctx.fillRect(x1,mid,x2-x1,chartArea.bottom-mid)}})}ctx.restore()}};
 new Chart(canvas,{type:"line",plugins:[bandPlugin],data:{datasets:cfg.datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"index",intersect:false},plugins:{legend:{position:"top",align:"end",labels:{color:"#b9cad7",usePointStyle:true,boxWidth:8}},tooltip:{enabled:true,mode:"index",intersect:false,callbacks:{title(items){if(!items.length)return"";return new Date(items[0].parsed.x).toLocaleString("de-AT")},label(ctx){return ctx.dataset.label+": "+Number(ctx.parsed.y).toLocaleString("de-AT",{maximumFractionDigits:1})+(ctx.dataset.yAxisID==="yPct"?" %":"")},afterBody(items){if(!items.length)return[];const t=items[0].parsed.x;return cfg.bands.map(b=>{let best=null,bd=Infinity;for(const p of b.pts){const d=Math.abs(Date.parse(p.time)-t);if(d<bd){bd=d;best=p}}const v=Number(best?.value??0),txt=b.kind==="state"?(v>0?"EIN":"AUS"):(v>0?"AUF":v<0?"ZU":"STILL");return b.label+": "+txt})}}}},scales:{x:{type:"linear",grid:{color:"#263949"},ticks:{color:"#7890a4",callback:v=>fmtTime(v),maxTicksLimit:6}},y:{position:"left",grid:{color:"#263949"},ticks:{color:"#7890a4"}},yPct:{display:hasPct,position:"right",min:0,max:100,grid:{drawOnChartArea:false},ticks:{color:"#7890a4",callback:v=>v+" %"}}}}})
}

function chart(block,d,ci){return '<article class="card preview-graph"><h2>'+esc(block.title)+'</h2>'+chartInner(block,d,ci)+'</article>'}
function nearest(pts,target){let b=null;for(const p of pts){const d=Math.abs(Date.parse(p.time)-target);if(!b||d<b.d)b={p,d}}return b?.p}

async function load(){const r=await fetch("/dev-portal/api/admin/dashboard-configs/"+id+"/preview-data?period="+period,{cache:"no-store"});if(!r.ok){document.body.innerHTML="<pre>Vorschau konnte nicht geladen werden: "+r.status+"</pre>";return}const d=await r.json();ptitle.textContent=d.name;pdesc.textContent=d.description||"";document.querySelectorAll("[data-period]").forEach(b=>b.classList.toggle("active",b.dataset.period===period));const cards=(d.blocks||[]).filter(b=>b.type==="card");const combos=(d.blocks||[]).map((b,blockIndex)=>({...b,_blockIndex:blockIndex})).filter(b=>b.type==="combo");pcards.innerHTML=cards.map(b=>'<article class="card"><h2>'+esc(b.title)+'</h2><div class="combo-live">'+(b.items||[]).map(it=>{const value=d.live[(it.source_index??0)+":"+it.key]??it.sample??"–",target=it.target_key?(d.live[(it.target_source_index??it.source_index??0)+":"+it.target_key]??it.target_sample):null,raw=Number(it.raw),on=Number.isFinite(raw)?raw>0:String(value).toLowerCase().includes("ein");let main=esc(value);if(it.live_display==="binary")main='<span class="status-dot '+(on?"on":"off")+'"></span>'+(on?"EIN":"AUS");else if(it.live_display==="percent")main='<span class="status-dot '+(Number(value)>0?"on":"off")+'"></span>'+esc(value);return'<div class="live-tile"><small>'+esc(it.label||it.key)+'</small><strong>'+main+'</strong>'+(target!=null&&target!==""?'<span class="live-target">Soll '+esc(String(target).match(/^8(?:[,.]0)?\s*°C$/)?"– °C":target)+'</span>':'')+'</div>'}).join("")+'</div></article>').join("")+combos.map((b,i)=>{const live={...b,items:(b.items||[]).filter(x=>x.scope==="live"||x.section==="live")},hist={...b,items:(b.items||[]).filter(x=>x.scope==="history"||x.section==="history")};return'<article class="card combo-card"><h2>'+esc(b.title)+'</h2><div class="combo-live">'+live.items.map(it=>{const value=d.live[(it.source_index??0)+":"+it.key]??it.sample??"–",target=it.target_key?(d.live[(it.target_source_index??it.source_index??0)+":"+it.target_key]??it.target_sample):null,raw=Number(it.raw),on=Number.isFinite(raw)?raw>0:String(value).toLowerCase().includes("ein");let main=esc(value);if(it.live_display==="binary")main='<span class="status-dot '+(on?"on":"off")+'"></span>'+(on?"EIN":"AUS");else if(it.live_display==="percent")main='<span class="status-dot '+(Number(value)>0?"on":"off")+'"></span>'+esc(value);return'<div class="live-tile"><small>'+esc(it.label||it.key)+'</small><strong>'+main+'</strong>'+(target!=null&&target!==""?'<span class="live-target">Soll '+esc(target)+'</span>':'')+'</div>'}).join("")+'</div><div class="combo-history">'+chartInner(hist,d,"combo"+b._blockIndex)+'</div></article>'}).join("");const graphs=(d.blocks||[]).filter(b=>b.type==="chart");historyTitle.style.display=graphs.length?"":"none";pgraphs.innerHTML=graphs.map((b,i)=>chart(b,d,"graph"+i)).join("");requestAnimationFrame(()=>{Object.keys(window.__chartConfigs||{}).forEach(renderChartJs)})}
load();document.querySelectorAll("[data-period]").forEach(b=>b.onclick=()=>{period=b.dataset.period;const u=new URL(location.href);u.searchParams.set("period",period);history.replaceState(null,"",u);load()});