const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const id=location.pathname.split("/").filter(Boolean).pop();let period=new URLSearchParams(location.search).get("period")||"24h";
const fmtTime=ts=>new Date(ts).toLocaleString("de-AT",period==="24h"?{hour:"2-digit",minute:"2-digit"}:{day:"2-digit",month:"2-digit",hour:"2-digit"});
function chartInner(block,d,ci){
 const datasets=[],bands=[];for(const it of block.items||[]){const pts=d.history[(it.source_index??0)+":"+it.key]||[],label=(it.label&&it.label.trim())?it.label.trim():it.key;if(!pts.length)continue;
  if(["binary","percent_binary"].includes(it.display)){bands.push({label,kind:"state",pts});continue}
  if(it.display==="mixer"){bands.push({label,kind:"mixer",pts});continue}
  const isPct=it.display==="percent"||String(it.key||"").includes("[%]");datasets.push({label,data:pts.map(p=>({x:Date.parse(p.time),y:p.value})),yAxisID:isPct?"yPct":"y",borderWidth:2,pointRadius:0,tension:.15,spanGaps:true})
 }
 if(!datasets.length&&!bands.length)return'<div class="pv-empty">Keine Daten im gewählten Zeitraum.</div>';
 window.__chartConfigs=window.__chartConfigs||{};window.__chartConfigs[String(ci)]={datasets,bands};
 return'<div class="chartjs-wrap"><canvas id="chartjs'+ci+'"></canvas></div>'
}
function renderChartJs(ci){
 const cfg=window.__chartConfigs?.[String(ci)],canvas=document.getElementById("chartjs"+ci);if(!cfg||!canvas||!window.Chart)return;
 const hasPct=cfg.datasets.some(x=>x.yAxisID==="yPct");
 const bandPlugin={id:"insEiBands",afterDatasetsDraw(chart,args,opt){const {ctx,chartArea,scales}=chart,x=scales.x;if(!x||!cfg.bands.length)return;const rowH=12,gap=6,total=cfg.bands.length*(rowH+gap),baseY=chartArea.bottom-total-2;ctx.save();ctx.font="11px sans-serif";ctx.textBaseline="middle";cfg.bands.forEach((b,bi)=>{const y=baseY+bi*(rowH+gap);ctx.fillStyle="#dce8f1";ctx.fillText(b.label,chartArea.left+2,y+rowH/2);const labelW=70,trackL=chartArea.left+labelW,trackR=chartArea.right;ctx.fillStyle="#091722";ctx.fillRect(trackL,y,trackR-trackL,rowH);b.pts.forEach((p,i)=>{const t=Date.parse(p.time),next=i+1<b.pts.length?Date.parse(b.pts[i+1].time):x.max,xx=Math.max(trackL,x.getPixelForValue(t)),xx2=Math.min(trackR,x.getPixelForValue(next));if(xx2<=xx)return;const v=Number(p.value);if(b.kind==="state")ctx.fillStyle=v>0?"#43d38c":"#091722";else ctx.fillStyle=v>0?"#e97855":v<0?"#3b8edb":"#091722";ctx.fillRect(xx,y,xx2-xx,rowH)})});ctx.restore()}};
 new Chart(canvas,{type:"line",plugins:[bandPlugin],data:{datasets:cfg.datasets},options:{responsive:true,maintainAspectRatio:false,layout:{padding:{bottom:cfg.bands.length*18+6}},interaction:{mode:"index",intersect:false},plugins:{legend:{position:"top",align:"end",labels:{color:"#b9cad7",usePointStyle:true,boxWidth:8}},tooltip:{enabled:true,mode:"index",intersect:false,callbacks:{title(items){if(!items.length)return"";return new Date(items[0].parsed.x).toLocaleString("de-AT")},label(ctx){return ctx.dataset.label+": "+Number(ctx.parsed.y).toLocaleString("de-AT",{maximumFractionDigits:1})+(ctx.dataset.yAxisID==="yPct"?" %":"")},afterBody(items){if(!items.length)return[];const t=items[0].parsed.x;return cfg.bands.map(b=>{let best=null,bd=Infinity;for(const p of b.pts){const d=Math.abs(Date.parse(p.time)-t);if(d<bd){bd=d;best=p}}const v=Number(best?.value??0),txt=b.kind==="state"?(v>0?"EIN":"AUS"):(v>0?"AUF":v<0?"ZU":"STILL");return b.label+": "+txt})}}}},scales:{x:{type:"linear",grid:{color:"#263949"},ticks:{color:"#7890a4",callback:v=>fmtTime(v),maxTicksLimit:6}},y:{position:"left",grid:{color:"#263949"},ticks:{color:"#7890a4"}},yPct:{display:hasPct,position:"right",min:0,max:100,grid:{drawOnChartArea:false},ticks:{color:"#7890a4",callback:v=>v+" %"}}}}})
}

function chart(block,d,ci){return '<article class="card preview-graph"><h2>'+esc(block.title)+'</h2>'+chartInner(block,d,ci)+'</article>'}
function nearest(pts,target){let b=null;for(const p of pts){const d=Math.abs(Date.parse(p.time)-target);if(!b||d<b.d)b={p,d}}return b?.p}

async function load(){const r=await fetch("/dev-portal/api/admin/dashboard-configs/"+id+"/preview-data?period="+period,{cache:"no-store"});if(!r.ok){document.body.innerHTML="<pre>Vorschau konnte nicht geladen werden: "+r.status+"</pre>";return}const d=await r.json();ptitle.textContent=d.name;pdesc.textContent=d.description||"";document.querySelectorAll("[data-period]").forEach(b=>b.classList.toggle("active",b.dataset.period===period));const cards=(d.blocks||[]).filter(b=>b.type==="card");const combos=(d.blocks||[]).filter(b=>b.type==="combo");pcards.innerHTML=cards.map(b=>'<article class="card"><h2>'+esc(b.title)+'</h2><div class="combo-live">'+(b.items||[]).map(it=>{const value=d.live[(it.source_index??0)+":"+it.key]??it.sample??"–",target=it.target_key?(d.live[(it.target_source_index??it.source_index??0)+":"+it.target_key]??it.target_sample):null,raw=Number(it.raw),on=Number.isFinite(raw)?raw>0:String(value).toLowerCase().includes("ein");let main=esc(value);if(it.live_display==="binary")main='<span class="status-dot '+(on?"on":"off")+'"></span>'+(on?"EIN":"AUS");else if(it.live_display==="percent")main='<span class="status-dot '+(Number(value)>0?"on":"off")+'"></span>'+esc(value);return'<div class="live-tile"><small>'+esc(it.label||it.key)+'</small><strong>'+main+'</strong>'+(target!=null&&target!==""?'<span class="live-target">Soll '+esc(String(target).match(/^8(?:[,.]0)?\s*°C$/)?"– °C":target)+'</span>':'')+'</div>'}).join("")+'</div></article>').join("")+combos.map((b,i)=>{const live={...b,items:(b.items||[]).filter(x=>x.scope==="live"||x.section==="live")},hist={...b,items:(b.items||[]).filter(x=>x.scope==="history"||x.section==="history")};return'<article class="card combo-card"><h2>'+esc(b.title)+'</h2><div class="combo-live">'+live.items.map(it=>{const value=d.live[(it.source_index??0)+":"+it.key]??it.sample??"–",target=it.target_key?(d.live[(it.target_source_index??it.source_index??0)+":"+it.target_key]??it.target_sample):null,raw=Number(it.raw),on=Number.isFinite(raw)?raw>0:String(value).toLowerCase().includes("ein");let main=esc(value);if(it.live_display==="binary")main='<span class="status-dot '+(on?"on":"off")+'"></span>'+(on?"EIN":"AUS");else if(it.live_display==="percent")main='<span class="status-dot '+(Number(value)>0?"on":"off")+'"></span>'+esc(value);return'<div class="live-tile"><small>'+esc(it.label||it.key)+'</small><strong>'+main+'</strong>'+(target!=null&&target!==""?'<span class="live-target">Soll '+esc(target)+'</span>':'')+'</div>'}).join("")+'</div><div class="combo-history">'+chartInner(hist,d,"combo"+i)+'</div></article>'}).join("");const graphs=(d.blocks||[]).filter(b=>b.type==="chart");historyTitle.style.display=graphs.length?"":"none";pgraphs.innerHTML=graphs.map((b,i)=>chart(b,d,"graph"+i)).join("");requestAnimationFrame(()=>{Object.keys(window.__chartConfigs||{}).forEach(renderChartJs)})}
load();document.querySelectorAll("[data-period]").forEach(b=>b.onclick=()=>{period=b.dataset.period;const u=new URL(location.href);u.searchParams.set("period",period);history.replaceState(null,"",u);load()});