const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const id=location.pathname.split("/").filter(Boolean).pop();let period=new URLSearchParams(location.search).get("period")||"24h";
const fmtTime=ts=>new Date(ts).toLocaleString("de-AT",period==="24h"?{hour:"2-digit",minute:"2-digit"}:{day:"2-digit",month:"2-digit",hour:"2-digit"});
function chart(block,d,ci){const lines=[],states=[],percents=[];for(const it of block.items||[]){const k=(it.source_index??0)+":"+it.key,pts=d.history[k]||[],label=it.label||it.key;if(["binary","percent_binary"].includes(it.display))states.push({label,pts});else if(it.display==="percent")percents.push({label,pts});else if(pts.length)lines.push({label,pts})}
 const all=[...lines,...states,...percents].flatMap(x=>x.pts);if(!all.length)return'<article class="card preview-graph"><h2>'+esc(block.title)+'</h2><div class="pv-empty">Keine Daten im gewählten Zeitraum.</div></article>';
 const times=all.map(p=>Date.parse(p.time)).filter(Number.isFinite),t0=Math.min(...times),t1=Math.max(...times),W=900,H=285,L=58,R=18,T=18,B=42,X=t=>L+(t-t0)/Math.max(1,t1-t0)*(W-L-R);
 let graph="";if(lines.length){const vals=lines.flatMap(x=>x.pts.map(p=>p.value)),rawMin=Math.min(...vals),rawMax=Math.max(...vals),pad=Math.max(1,(rawMax-rawMin)*.12);let mn=Math.floor((rawMin-pad)/5)*5,mx=Math.ceil((rawMax+pad)/5)*5;if(mx<=mn)mx=mn+5;const Y=v=>T+(mx-v)/(mx-mn)*(H-T-B),yticks=Array.from({length:5},(_,i)=>mn+(mx-mn)*i/4),grid=yticks.map(v=>{const y=Y(v);return'<line class="pv-grid" x1="'+L+'" y1="'+y+'" x2="'+(W-R)+'" y2="'+y+'"/><text class="pv-axis" x="'+(L-8)+'" y="'+(y+3)+'" text-anchor="end">'+v.toFixed(v%1?1:0)+'</text>'}).join(""),xticks=Array.from({length:5},(_,i)=>t0+(t1-t0)*i/4).map((t,i)=>'<text class="pv-axis" x="'+X(t)+'" y="'+(H-10)+'" text-anchor="'+(i===0?"start":i===4?"end":"middle")+'">'+esc(fmtTime(t))+'</text>').join(""),paths=lines.map((x,i)=>'<path class="pv-line pv-c'+i%6+'" d="'+x.pts.map((p,j)=>(j?"L":"M")+X(Date.parse(p.time)).toFixed(1)+" "+Y(p.value).toFixed(1)).join(" ")+'"/>').join("");graph='<div class="pv-legend">'+lines.map((x,i)=>'<span class="pv-t'+i%6+'">'+esc(x.label)+'</span>').join("")+'</div><div class="pv-chart-wrap"><svg class="pv-svg" viewBox="0 0 '+W+' '+H+'">'+grid+xticks+paths+'<line class="pv-cross" x1="0" y1="'+T+'" x2="0" y2="'+(H-B)+'"/></svg><div class="pv-tip"></div></div>'}
 const bands=states.map((x,si)=>{const seg=x.pts.map((p,i)=>{const t=Date.parse(p.time),next=i+1<x.pts.length?Date.parse(x.pts[i+1].time):t1,left=(t-t0)/Math.max(1,t1-t0)*100,width=Math.max(.15,(next-t)/Math.max(1,t1-t0)*100);return'<i class="'+(p.value>0?"on":"off")+'" style="left:'+left+'%;width:'+width+'%" title="'+esc(fmtTime(t))+' · '+(p.value>0?"EIN":"AUS")+'"></i>'}).join("");return'<div class="pv-band" data-label="'+esc(x.label)+'"><span>'+esc(x.label)+'</span><div class="pv-band-track">'+seg+'</div></div>'}).join("");
 const pct=percents.map(x=>'<div class="pv-percent"><span>'+esc(x.label)+'</span><div class="pv-percent-track">'+x.pts.map((p,i)=>{const t=Date.parse(p.time),next=i+1<x.pts.length?Date.parse(x.pts[i+1].time):t1,left=(t-t0)/Math.max(1,t1-t0)*100,width=Math.max(.15,(next-t)/Math.max(1,t1-t0)*100);return'<i style="left:'+left+'%;width:'+width+'%;height:'+Math.max(1,Math.min(100,p.value))+'%" title="'+esc(fmtTime(t))+' · '+p.value.toFixed(0)+' %"></i>'}).join("")+'</div></div>').join("");
 setTimeout(()=>bindHover("pvchart"+ci,{lines,states,percents,t0,t1,W,L,R}),0);return'<article class="card preview-graph" id="pvchart'+ci+'"><h2>'+esc(block.title)+'</h2>'+graph+bands+pct+'</article>'}
function nearest(pts,target){let b=null;for(const p of pts){const d=Math.abs(Date.parse(p.time)-target);if(!b||d<b.d)b={p,d}}return b?.p}
function bindHover(id,cfg){const card=document.getElementById(id),svg=card?.querySelector(".pv-svg");if(!svg)return;const tip=card.querySelector(".pv-tip"),cross=card.querySelector(".pv-cross");svg.onmousemove=e=>{const r=svg.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*cfg.W,ratio=Math.max(0,Math.min(1,(px-cfg.L)/(cfg.W-cfg.L-cfg.R))),target=cfg.t0+ratio*(cfg.t1-cfg.t0),x=cfg.L+ratio*(cfg.W-cfg.L-cfg.R);cross.setAttribute("x1",x);cross.setAttribute("x2",x);cross.classList.add("show");let html='<b>'+esc(new Date(target).toLocaleString("de-AT",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}))+'</b>';for(const s of [...cfg.lines,...cfg.percents]){const p=nearest(s.pts,target);if(p)html+='<div><span>'+esc(s.label)+'</span><strong>'+p.value.toFixed(1)+(cfg.percents.includes(s)?" %":"")+'</strong></div>'}for(const s of cfg.states){const p=nearest(s.pts,target);if(p)html+='<div><span>'+esc(s.label)+'</span><strong>'+(p.value>0?"EIN":"AUS")+'</strong></div>'}tip.innerHTML=html;tip.classList.add("show");tip.style.left=Math.min(r.width-210,Math.max(8,e.clientX-r.left+14))+"px";tip.style.top=Math.max(8,e.clientY-r.top-45)+"px"};svg.onmouseleave=()=>{tip.classList.remove("show");cross.classList.remove("show")}}
async function load(){const r=await fetch("/dev-portal/api/admin/dashboard-configs/"+id+"/preview-data?period="+period,{cache:"no-store"});if(!r.ok){document.body.innerHTML="<pre>Vorschau konnte nicht geladen werden: "+r.status+"</pre>";return}const d=await r.json();ptitle.textContent=d.name;pdesc.textContent=d.description||"";document.querySelectorAll("[data-period]").forEach(b=>b.classList.toggle("active",b.dataset.period===period));const cards=(d.blocks||[]).filter(b=>b.type==="card");pcards.innerHTML=cards.map(b=>'<article class="card"><h2>'+esc(b.title)+'</h2>'+(b.items||[]).map(it=>'<div class="oek-live-row"><span>'+esc(it.label||it.key)+'</span><strong>'+esc(d.live[(it.source_index??0)+":"+it.key]??it.sample??"–")+'</strong></div>').join("")+'</article>').join("");const graphs=(d.blocks||[]).filter(b=>b.type==="chart");historyTitle.style.display=graphs.length?"":"none";pgraphs.innerHTML=graphs.map((b,i)=>chart(b,d,i)).join("")}
load();document.querySelectorAll("[data-period]").forEach(b=>b.onclick=()=>{period=b.dataset.period;const u=new URL(location.href);u.searchParams.set("period",period);history.replaceState(null,"",u);load()});