const API="/api/v1/telemetry/status";let latest={};
const fmt=(v,u="")=>v===undefined||v===null?"–":`${typeof v==="number"?Math.round(v*100)/100:v}${u}`;
const cv=(x,k,u="")=>fmt(x?.current?.[k],u);
const metric=(n,v)=>`<div class="metric"><small>${n}</small><strong>${v}</strong></div>`;
function card(x){return `<article class="card clickable" data-id="${x.installation_id}"><div class="card-head"><div><h2>${x.installation_id}</h2><span class="status ${x.online?"online":"offline"}">● ${x.online?"Online":"Offline"}</span></div><span class="open">Details →</span></div><div class="metrics">${metric("Batterie SOC",cv(x,"battery.soc"," %"))}${metric("Batterieleistung",cv(x,"battery.power"," W"))}${metric("PV",cv(x,"pv.power"," W"))}${metric("Netz",cv(x,"grid.power"," W"))}${metric("Puffer oben",cv(x,"buffer.temperature_upper"," °C"))}${metric("Warmwasser",cv(x,"dhw.temperature"," °C"))}</div><div class="meta">Letzter Kontakt vor ${x.age_seconds}s · Samples: ${x.sample_count}<br>Optimierer: ${cv(x,"shadow.action")}</div></article>`}
const groups=[
["Energie",[["PV","pv.power"," W"],["Netz","grid.power"," W"],["Batterie","battery.power"," W"],["Spotpreis","MARKET.spot_price"," €/kWh"]]],
["Batterie",[["SOC","battery.soc"," %"],["SOH","battery.soh"," %"],["Spannung","battery.voltage"," V"],["Strom","battery.current"," A"],["Temperatur","battery.temperature"," °C"],["Module online","battery.modules_online",""]]],
["Wärme",[["Puffer oben","buffer.temperature_upper"," °C"],["Warmwasser","dhw.temperature"," °C"],["Außen","weather.outdoor_temperature"," °C"]]],
["Prognose",[["PV heute","forecast.pv_today"," kWh"],["PV aktuelle Stunde","forecast.pv_current_hour"," kWh"],["Verbrauch heute","forecast.consumption_today"," kWh"],["Verbrauch aktuelle Stunde","forecast.consumption_current_hour"," kWh"]]],
["Optimierer",[["Aktion","shadow.action",""],["Konfidenz","shadow.confidence",""]]]
];
async function openDetail(id){const x=latest.installations.find(i=>i.installation_id===id);if(!x)return;detailBody.innerHTML=`<div class="detail-head"><div><h1>${id}</h1><span class="status ${x.online?"online":"offline"}">● ${x.online?"Online":"Offline"}</span></div><div class="meta">Letzter Kontakt vor ${x.age_seconds}s<br>${x.sample_count} Samples</div></div><div class="group-grid">${groups.map(([title,items])=>`<section class="group"><h3>${title}</h3><div class="metrics">${items.map(([n,k,u])=>metric(n,cv(x,k,u))).join("")}</div></section>`).join("")}</div><section class="group"><h3>Batteriealarme</h3><div class="alarm-list">${Object.entries(x.current||{}).filter(([k])=>k.startsWith("battery.alarm")).map(([k,v])=>`<span class="${v==="no_alarm"?"good":"bad"}">${k.replace("battery.alarm_","").replaceAll("_"," ")}: ${v}</span>`).join("")||"–"}</div></section><section class="group history"><div class="history-head"><h3>Historie</h3><div class="periods"><button data-period="24h" class="selected">24 h</button><button data-period="7d">7 Tage</button><button data-period="30d">30 Tage</button></div></div><div id="charts" class="charts"><div class="loading">Lade Zeitreihen …</div></div></section>`;detail.classList.remove("hidden");document.querySelectorAll(".periods button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".periods button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");loadHistory(id,b.dataset.period)});await loadHistory(id,"24h")}
function bind(){document.querySelectorAll(".clickable").forEach(c=>c.onclick=()=>openDetail(c.dataset.id))}
async function load(){try{const r=await fetch(API);if(!r.ok)throw Error(r.status);latest=await r.json();count.textContent=latest.count;online.textContent=latest.online;offline.textContent=latest.count-latest.online;cards.innerHTML=latest.installations.map(card).join("")||'<div class="loading">Noch keine Instanzen.</div>';api.textContent="API online";api.classList.add("ok");bind()}catch(e){api.textContent="API offline";api.classList.remove("ok");cards.innerHTML='<div class="loading">INS-EI API nicht erreichbar.</div>'}}
document.getElementById("close").addEventListener("click",()=>detail.classList.add("hidden"));detail.addEventListener("click",e=>{if(e.target===detail)detail.classList.add("hidden")});load();setInterval(load,30000);
const chartDefs=[
 ["Leistung","W",["pv.power","grid.power","battery.power"]],
 ["Batterie SOC","%",["battery.soc"]],
 ["Temperaturen","°C",["buffer.temperature_upper","dhw.temperature","weather.outdoor_temperature"]]
];
const labels={"pv.power":"PV","grid.power":"Netz","battery.power":"Batterie","battery.soc":"SOC","buffer.temperature_upper":"Puffer","dhw.temperature":"Warmwasser","weather.outdoor_temperature":"Außen"};
function svgChart(title,unit,fields,series){const all=fields.flatMap(f=>(series[f]||[]).map(p=>p.value));if(!all.length)return `<div class="chart"><h4>${title}</h4><div class="loading">Keine Daten</div></div>`;let min=Math.min(...all),max=Math.max(...all);if(min===max){min-=1;max+=1}const W=720,H=230,P=35;const times=fields.flatMap(f=>(series[f]||[]).map(p=>Date.parse(p.time))).filter(Number.isFinite);const t0=Math.min(...times),t1=Math.max(...times);const x=t=>P+(Date.parse(t)-t0)/(t1-t0||1)*(W-2*P);const y=v=>H-P-(v-min)/(max-min)*(H-2*P);const paths=fields.map((f,i)=>{const pts=(series[f]||[]).map(p=>`${x(p.time).toFixed(1)},${y(p.value).toFixed(1)}`).join(" ");return pts?`<polyline class="line l${i}" points="${pts}"/>`:""}).join("");const legend=fields.map((f,i)=>`<span class="legend l${i}">${labels[f]||f}</span>`).join("");return `<div class="chart"><div class="chart-title"><h4>${title}</h4><span>${min.toFixed(1)}–${max.toFixed(1)} ${unit}</span></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="${P}" y1="${H-P}" x2="${W-P}" y2="${H-P}" class="axis"/>${paths}</svg><div class="legend-row">${legend}</div></div>`}
async function loadHistory(id,period){const box=document.getElementById("charts");if(!box)return;box.innerHTML='<div class="loading">Lade Zeitreihen …</div>';try{const r=await fetch(`/api/v1/telemetry/history/${encodeURIComponent(id)}?period=${period}`);if(!r.ok)throw Error(r.status);const d=await r.json();box.innerHTML=chartDefs.map(([t,u,f])=>svgChart(t,u,f,d.series)).join("")}catch(e){box.innerHTML='<div class="loading">Historie konnte nicht geladen werden.</div>'}}

const customerPage=document.getElementById("customers"), instanceSection=document.getElementById("instances"), statsSection=document.querySelector(".stats"), navCustomers=document.getElementById("navCustomers"), navDashboard=document.getElementById("navDashboard"), navInstances=document.getElementById("navInstances"), customerRows=document.getElementById("customerRows"), customerCount=document.getElementById("customerCount"), customerSearch=document.getElementById("customerSearch"), newCustomer=document.getElementById("newCustomer");
function setView(view){
  detail.classList.add("hidden");
  customerPage.classList.toggle("hidden",view!=="customers");
  instanceSection.classList.toggle("hidden",view==="customers");
  statsSection.classList.toggle("hidden",view==="customers");
  document.querySelectorAll("nav a").forEach(x=>x.classList.remove("active"));
  (view==="customers"?navCustomers:(view==="instances"?navInstances:navDashboard)).classList.add("active");
  if(view==="customers") loadCustomers(customerSearch.value.trim());
}
function navigate(view){setView(view);history.replaceState(null,"","#"+view)}
navDashboard.addEventListener("click",e=>{e.preventDefault();navigate("dashboard")});
navInstances.addEventListener("click",e=>{e.preventDefault();navigate("instances")});
navCustomers.addEventListener("click",e=>{e.preventDefault();navigate("customers")});
window.addEventListener("hashchange",()=>setView(location.hash.slice(1)||"dashboard"));
async function loadCustomers(q=""){customerRows.innerHTML='<tr><td colspan="6" class="loading">Lade Kunden …</td></tr>';try{const r=await fetch("/api/v1/customers"+(q?"?q="+encodeURIComponent(q):""));if(!r.ok)throw Error(r.status);const d=await r.json();customerCount.textContent=d.count+" Kunden";customerRows.innerHTML=d.customers.map(c=>`<tr class="customer-row" data-customer="${c.id}"><td><strong>${c.name}</strong></td><td>${c.address||"–"}</td><td>${[c.postal_code,c.city].filter(Boolean).join(" ")||"–"}</td><td>${c.phone||"–"}</td><td>${c.email||"–"}</td><td class="open">Details →</td></tr>`).join("")||'<tr><td colspan="6" class="loading">Noch keine Kunden erfasst.</td></tr>';document.querySelectorAll(".customer-row").forEach(x=>x.onclick=()=>openCustomer(x.dataset.customer))}catch(e){customerRows.innerHTML='<tr><td colspan="6" class="loading">Kunden konnten nicht geladen werden.</td></tr>'}}
let customerTimer;customerSearch.oninput=()=>{clearTimeout(customerTimer);customerTimer=setTimeout(()=>loadCustomers(customerSearch.value.trim()),200)};
async function openCustomer(id){const r=await fetch("/api/v1/customers/"+id);if(!r.ok)return;const c=await r.json();detailBody.innerHTML=`<div class="detail-head"><div><h1>${c.name}</h1><span class="status online">Kunde #${c.id}</span></div><button id="editCustomer" class="secondary">Bearbeiten</button></div><div class="customer-tabs"><button class="selected">Übersicht</button><button>Anlagen</button><button>Einsätze</button><button>Wartungen</button><button>Dokumente</button><button>🔒 Zugangsdaten</button></div><section class="group"><h3>Stammdaten</h3><div class="customer-detail-grid"><div><small>Adresse</small><strong>${c.address||"–"}</strong></div><div><small>PLZ / Ort</small><strong>${[c.postal_code,c.city].filter(Boolean).join(" ")||"–"}</strong></div><div><small>Telefon</small><strong>${c.phone||"–"}</strong></div><div><small>E-Mail</small><strong>${c.email||"–"}</strong></div></div></section><section class="group"><h3>Notizen</h3><p>${c.notes||"–"}</p></section><section class="group"><div class="history-head"><h3>Anlagen</h3><button id="addDevice" class="primary">+ Anlage hinzufügen</button></div><div class="device-list">${c.devices?.length?c.devices.map(deviceCard).join(""):'<div class="loading">Noch keine Anlagen zugeordnet.</div>'}</div></section>`;detail.classList.remove("hidden");document.getElementById("editCustomer").onclick=()=>editCustomerForm(c);document.getElementById("addDevice").onclick=()=>addDeviceForm(c)}
function deviceCard(d){return `<div class="device-card"><strong>${d.manufacturer||"Anlage"} ${d.model||""}</strong><span>Kesselnummer: ${d.serial_number||"–"}</span><span>Touch-ID: ${d.touch_id||"–"}</span><span>Baujahr: ${d.construction_year||"–"} · Leistung: ${d.power_kw??"–"} kW</span></div>`}
function addDeviceForm(customer){detailBody.innerHTML=`<div class="detail-head"><div><h1>Anlage hinzufügen</h1><span class="meta">${customer.name}</span></div></div><form id="deviceForm" class="customer-form"><label>Hersteller<select name="manufacturer"><option>ÖkoFEN</option><option>Andere</option></select></label><label>Modell / Typ<input name="model" placeholder="z. B. PEK325"></label><label>Kesselnummer<input name="serial_number" placeholder="z. B. X149716"></label><label>Touch-ID<input name="touch_id" placeholder="z. B. P0060B5_50EA9D"></label><div class="form-row"><label>Baujahr<input name="construction_year" type="number" min="1980" max="2100"></label><label>Leistung kW<input name="power_kw" type="number" step="0.1" min="0"></label></div><label>Inbetriebnahmedatum (optional)<input name="commissioning_date" type="date"></label><label>Notizen<textarea name="notes" rows="4"></textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancelDevice">Abbrechen</button><button type="submit" class="primary">Anlage speichern</button></div></form>`;detail.classList.remove("hidden");cancelDevice.onclick=()=>openCustomer(customer.id);deviceForm.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(deviceForm).entries());if(!data.construction_year)delete data.construction_year;else data.construction_year=Number(data.construction_year);if(!data.power_kw)delete data.power_kw;else data.power_kw=Number(data.power_kw);if(!data.commissioning_date)delete data.commissioning_date;const r=await fetch("/api/v1/customers/"+customer.id+"/devices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(r.ok)openCustomer(customer.id);else alert("Anlage konnte nicht gespeichert werden.")}}
function editCustomerForm(c){detailBody.innerHTML=`<div class="detail-head"><div><h1>Kunde bearbeiten</h1><span class="meta">#${c.id}</span></div></div><form id="customerEditForm" class="customer-form"><label>Name / Firma<input name="name" required value="${esc(c.name)}"></label><label>Adresse<input name="address" value="${esc(c.address)}"></label><div class="form-row"><label>PLZ<input name="postal_code" value="${esc(c.postal_code)}"></label><label>Ort<input name="city" value="${esc(c.city)}"></label></div><label>Telefon<input name="phone" type="tel" value="${esc(c.phone)}"></label><label>E-Mail<input name="email" type="email" value="${esc(c.email)}"></label><label>Notizen<textarea name="notes" rows="5">${esc(c.notes)}</textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancelEdit">Abbrechen</button><button type="submit" class="primary">Änderungen speichern</button></div></form>`;cancelEdit.onclick=()=>openCustomer(c.id);customerEditForm.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(customerEditForm).entries());const r=await fetch("/api/v1/customers/"+c.id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(r.ok){await loadCustomers(customerSearch.value.trim());openCustomer(c.id)}else alert("Änderungen konnten nicht gespeichert werden.")}}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
newCustomer.onclick=()=>{detailBody.innerHTML=`<div class="detail-head"><div><h1>Kunde anlegen</h1><span class="meta">Stammdaten</span></div></div><form id="customerForm" class="customer-form"><label>Name / Firma<input name="name" required autofocus></label><label>Ansprechpartner<input name="contact_person"></label><label>Adresse<input name="address"></label><div class="form-row"><label>PLZ<input name="postal_code"></label><label>Ort<input name="city"></label></div><label>Telefon<input name="phone" type="tel"></label><label>E-Mail<input name="email" type="email"></label><label>Notizen<textarea name="notes" rows="5"></textarea></label><div class="form-actions"><button type="button" class="secondary" id="cancelCustomer">Abbrechen</button><button type="submit" class="primary">Kunde speichern</button></div></form>`;detail.classList.remove("hidden");cancelCustomer.onclick=()=>detail.classList.add("hidden");customerForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(customerForm),data=Object.fromEntries(fd.entries());delete data.contact_person;const r=await fetch("/api/v1/customers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(r.ok){detail.classList.add("hidden");loadCustomers(customerSearch.value.trim())}else alert("Kunde konnte nicht gespeichert werden.")}};
setView(["customers","instances"].includes(location.hash.slice(1))?location.hash.slice(1):"dashboard");
