const API="/api/v1/telemetry/status";let latest={};
const fmt=(v,u="")=>v===undefined||v===null?"–":`${typeof v==="number"?Math.round(v*100)/100:v}${u}`;
const cv=(x,k,u="")=>fmt(x?.current?.[k],u);
const metric=(n,v)=>`<div class="metric"><small>${n}</small><strong>${v}</strong></div>`;
function card(x){return `<article class="card clickable" data-id="${x.installation_id}"><div class="card-head"><div><h2>${x.installation_id}</h2><span class="status ${x.online?"online":"offline"}">● ${x.online?"Online":"Offline"}</span></div><span class="open">Details →</span></div><div class="metrics">${metric("Batterie SOC",cv(x,"battery.soc"," %"))}${metric("Batterieleistung",cv(x,"battery.power"," W"))}${metric("PV",cv(x,"pv.power"," W"))}${metric("Netz",cv(x,"grid.power"," W"))}${metric("Puffer oben",cv(x,"buffer.temperature_upper"," °C"))}${metric("Warmwasser",cv(x,"dhw.temperature"," °C"))}</div><div class="meta">Letzter Kontakt vor ${x.age_seconds}s · Samples: ${x.sample_count}<br>Optimierer: ${cv(x,"shadow.action")}</div></article>`}
const groups=[
["Energie",[["PV","pv.power"," W"],["Netz","grid.power"," W"],["Batterie","battery.power"," W"],["Spotpreis","MARKET.spot_price"," €/kWh"]]],
["Batterie",[["SOC","battery.soc"," %"],["SOH","battery.soh"," %"],["Spannung","battery.voltage"," V"],["Strom","battery.current"," A"],["Temperatur","battery.temperature"," °C"],["Module online","battery.modules_online",""]]],
["Wärme",[["Puffer oben","buffer.temperature_upper"," °C"],["Warmwasser","dhw.temperature"," °C"],["Außen","weather.outdoor_temperature"," °C"]]],
["Prognose",[["PV heute","forecast.pv_today"," kWh"],["PV aktuelle Stunde","forecast.pv_current_hour"," kWh"],["Verbrauch heute","forecast.consumption_today"," kWh"],["Verbrauch aktuelle Stunde","forecast.consumption_current_hour"," kWh"]]],
["Optimierer",[["Aktion","shadow.action",""],["Konfidenz","shadow.confidence",""]]]
];
async function openDetail(id){const x=latest.installations.find(i=>i.installation_id===id);if(!x)return;detailBody.innerHTML=`<div class="detail-head"><div><h1>${id}</h1><span class="status ${x.online?"online":"offline"}">● ${x.online?"Online":"Offline"}</span></div><div class="meta">Letzter Kontakt vor ${x.age_seconds}s<br>${x.sample_count} Samples</div></div><div class="group-grid">${groups.map(([title,items])=>`<section class="group"><h3>${title}</h3><div class="metrics">${items.map(([n,k,u])=>metric(n,cv(x,k,u))).join("")}</div></section>`).join("")}</div><section class="group"><h3>Batteriealarme</h3><div class="alarm-list">${Object.entries(x.current||{}).filter(([k])=>k.startsWith("battery.alarm")).map(([k,v])=>`<span class="${v==="no_alarm"?"good":"bad"}">${k.replace("battery.alarm_","").replaceAll("_"," ")}: ${v}</span>`).join("")||"–"}</div></section><section class="group history"><div class="history-head"><h3>Historie</h3><div class="periods"><button data-period="24h" class="selected">24 h</button><button data-period="7d">7 Tage</button><button data-period="30d">30 Tage</button></div></div><div id="charts" class="charts"><div class="loading">Lade Zeitreihen …</div></div></section>`;detail.classList.remove("hidden");document.querySelectorAll(".periods button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".periods button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");loadHistory(id,b.dataset.period)});await loadHistory(id,"24h")}
function bind(){document.querySelectorAll(".clickable").forEach(c=>c.onclick=()=>openDetail(c.dataset.id))}
async function load(){try{const r=await fetch(API);if(!r.ok)throw Error(r.status);latest=await r.json();count.textContent=latest.count;online.textContent=latest.online;offline.textContent=latest.count-latest.online;cards.innerHTML=latest.installations.map(card).join("")||'<div class="loading">Noch keine Instanzen.</div>';api.textContent="API online";api.classList.add("ok");bind()}catch(e){api.textContent="API offline";api.classList.remove("ok");cards.innerHTML='<div class="loading">INS-EI API nicht erreichbar.</div>'}}
close.onclick=()=>detail.classList.add("hidden");detail.onclick=e=>{if(e.target===detail)detail.classList.add("hidden")};load();setInterval(load,30000);
const chartDefs=[
 ["Leistung","W",["pv.power","grid.power","battery.power"]],
 ["Batterie SOC","%",["battery.soc"]],
 ["Temperaturen","°C",["buffer.temperature_upper","dhw.temperature","weather.outdoor_temperature"]]
];
const labels={"pv.power":"PV","grid.power":"Netz","battery.power":"Batterie","battery.soc":"SOC","buffer.temperature_upper":"Puffer","dhw.temperature":"Warmwasser","weather.outdoor_temperature":"Außen"};
function svgChart(title,unit,fields,series){const all=fields.flatMap(f=>(series[f]||[]).map(p=>p.value));if(!all.length)return `<div class="chart"><h4>${title}</h4><div class="loading">Keine Daten</div></div>`;let min=Math.min(...all),max=Math.max(...all);if(min===max){min-=1;max+=1}const W=720,H=230,P=35;const times=fields.flatMap(f=>(series[f]||[]).map(p=>Date.parse(p.time))).filter(Number.isFinite);const t0=Math.min(...times),t1=Math.max(...times);const x=t=>P+(Date.parse(t)-t0)/(t1-t0||1)*(W-2*P);const y=v=>H-P-(v-min)/(max-min)*(H-2*P);const paths=fields.map((f,i)=>{const pts=(series[f]||[]).map(p=>`${x(p.time).toFixed(1)},${y(p.value).toFixed(1)}`).join(" ");return pts?`<polyline class="line l${i}" points="${pts}"/>`:""}).join("");const legend=fields.map((f,i)=>`<span class="legend l${i}">${labels[f]||f}</span>`).join("");return `<div class="chart"><div class="chart-title"><h4>${title}</h4><span>${min.toFixed(1)}–${max.toFixed(1)} ${unit}</span></div><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line x1="${P}" y1="${H-P}" x2="${W-P}" y2="${H-P}" class="axis"/>${paths}</svg><div class="legend-row">${legend}</div></div>`}
async function loadHistory(id,period){const box=document.getElementById("charts");if(!box)return;box.innerHTML='<div class="loading">Lade Zeitreihen …</div>';try{const r=await fetch(`/api/v1/telemetry/history/${encodeURIComponent(id)}?period=${period}`);if(!r.ok)throw Error(r.status);const d=await r.json();box.innerHTML=chartDefs.map(([t,u,f])=>svgChart(t,u,f,d.series)).join("")}catch(e){box.innerHTML='<div class="loading">Historie konnte nicht geladen werden.</div>'}}
