const INSAuth=(()=>{
const b64buf=s=>{s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a.buffer};
const b64url=b=>{const a=new Uint8Array(b);let s="";a.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")};
const jsonCredential=c=>({id:c.id,rawId:b64url(c.rawId),type:c.type,response:{clientDataJSON:b64url(c.response.clientDataJSON),attestationObject:c.response.attestationObject?b64url(c.response.attestationObject):undefined,authenticatorData:c.response.authenticatorData?b64url(c.response.authenticatorData):undefined,signature:c.response.signature?b64url(c.response.signature):undefined,userHandle:c.response.userHandle?b64url(c.response.userHandle):null},clientExtensionResults:c.getClientExtensionResults()});
function prepCreate(o){o.challenge=b64buf(o.challenge);o.user.id=b64buf(o.user.id);(o.excludeCredentials||[]).forEach(x=>x.id=b64buf(x.id));return o}
function prepGet(o){o.challenge=b64buf(o.challenge);(o.allowCredentials||[]).forEach(x=>x.id=b64buf(x.id));return o}
async function post(url,body={}){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||("HTTP "+r.status));return d}
async function register(){const d=await post("/api/v1/auth/register/options");const c=await navigator.credentials.create({publicKey:prepCreate(d.options)});await post("/api/v1/auth/register/verify",{token:d.token,...jsonCredential(c)});location.reload()}
async function login(){const d=await post("/api/v1/auth/login/options");const c=await navigator.credentials.get({publicKey:prepGet(d.options)});await post("/api/v1/auth/login/verify",{token:d.token,...jsonCredential(c)});location.reload()}
async function init(){const box=document.getElementById("serviceAuth"),btn=document.getElementById("serviceAuthButton"),msg=document.getElementById("serviceAuthMessage");try{const r=await fetch("/api/v1/auth/status?t="+Date.now(),{cache:"no-store"}),d=await r.json();if(d.authenticated){document.body.classList.remove("service-locked");box.classList.add("hidden");return}document.body.classList.add("service-locked");box.classList.remove("hidden");if(!window.PublicKeyCredential){msg.textContent="Dieses Gerät unterstützt keine Passkeys.";btn.disabled=true;return}btn.disabled=false;if(d.configured){msg.textContent="Mit Face ID, Touch ID oder Windows Hello anmelden.";btn.textContent="Mit Passkey anmelden";btn.onclick=async()=>{btn.disabled=true;msg.textContent="Passkey wird vorbereitet …";try{await login()}catch(e){msg.textContent="Anmeldung fehlgeschlagen: "+e.message;btn.disabled=false}}}else{msg.textContent="Noch kein Administrator-Passkey eingerichtet. Richte jetzt den ersten Passkey ein.";btn.textContent="Ersten Passkey einrichten";btn.onclick=async()=>{btn.disabled=true;msg.textContent="Passkey wird vorbereitet …";try{await register()}catch(e){msg.textContent="Einrichtung fehlgeschlagen: "+e.message;btn.disabled=false}}}}catch(e){document.body.classList.add("service-locked");box.classList.remove("hidden");msg.textContent="Authentifizierungsdienst nicht erreichbar: "+e.message}}
return{init,login,register}})();
INSAuth.init();
