"""Stable contracts for optional INS-EI plugins."""
from dataclasses import dataclass,field
from enum import Enum
from typing import Any,Protocol
class PluginKind(str,Enum): DEVICE="DEVICE";INTERFACE="INTERFACE"
@dataclass(frozen=True)
class PluginManifest:
    plugin_id:str;name:str;version:str;kind:PluginKind;description:str="";multi_instance:bool=True
@dataclass(frozen=True)
class InputDescriptor: point_id:str;name:str;unit:str|None=None;description:str=""
@dataclass(frozen=True)
class ActuatorDescriptor: actuator_id:str;name:str;capability:str;description:str="";restorable:bool=True
@dataclass
class PluginHealth: connected:bool;message:str="";last_success:str|None=None;diagnostics:dict[str,Any]=field(default_factory=dict)
class PluginInstance(Protocol):
    instance_id:str
    def manifest(self)->PluginManifest: ...
    def inputs(self)->list[InputDescriptor]: ...
    def actuators(self)->list[ActuatorDescriptor]: ...
    def read_points(self)->dict[str,Any]: ...
    def read_actuator(self,actuator_id:str)->Any: ...
    def write_actuator(self,actuator_id:str,value:Any)->None: ...
    def verify_actuator(self,actuator_id:str,value:Any)->bool: ...
    def health(self)->PluginHealth: ...
